### ISSUE TITLE
hETH Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#101]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0x5A2295f0b8A1f2b9bF26b9549Ce808c68e1a3F5f#readProxyContract

### Protocol Documentation

https://docs.hord.fi/heth

### Protocol Audits

https://docs.hord.fi/security/smart-contract-audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract & all involved downstream contracts are verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
Waiting for feedback on the verification of a downstream contract.

**Comment by Zen-Maxi** [comment]
Current outstanding task is for Hord to either verify the HordeStakingManager contract https://etherscan.io/address/0xc1e887a3fa7c1413f8ae0a9947a363f8865d387f#code or for Balancer to accept a closed source review process and maintain various warnings on the frontend to maintain transparency with liquidity providers.

**Comment by Zen-Maxi** [comment]
The issue will be closed because the protocol is closed source and will not be transparent for LPs to monitor the state of the rate provider after launch.
