### ISSUE TITLE
sUSX Rate Providers

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#102]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xc497F11326c3DE5086710EDa43354697b32c1541

### Additional Links

https://arbiscan.io/address/0xf7ec24690fBCEc489E7C9A7055C04Db5C221c397

### Protocol Documentation

https://medium.com/dforcenet/usx-becomes-the-first-ever-native-yield-bearing-omni-stablecoin-73e9a7485a97

### Protocol Audits

https://github.com/dforce-network/documents/tree/master/audit_report/Lending

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract & all involved downstream contracts are verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by Donald-Nobel** [comment]
Appending doc link, https://docs.usx.finance/susx
