### ISSUE TITLE
pzETH Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#104]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0x34406A8Ee75B5af34F8920D1960AC6a5B33A47b6#readContract

### Additional Links

https://etherscan.io/address/0x2A2f1b8c02Dafc5359B8E0e8BFc138400CB6d3a1#readContract

### Protocol Documentation

https://docs.mellow.finance/

### Protocol Audits

https://docs.mellow.finance/mellow-lrt-primitive/audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract & all involved downstream contracts are verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
https://github.com/balancer/code-review/pull/109
