### ISSUE TITLE
sDOLA ERC4626 Rate Provider

### ISSUE THREAD

**Issue by cryptoharry** [balancer/code-review#13]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xd02011c6c8aee310d0aa42aa98bfe9dca547fcc0

### Additional Links

sDOLA: https://etherscan.io/address/0xb45ad160634c528Cc3D2926d9807104FA3157305

### Protocol Documentation

https://docs.inverse.finance/inverse-finance/inverse-finance/product-guide/tokens/sdola

### Protocol Audits

https://www.inverse.finance/audits/sDOLA-yAudit.pdf

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by Tritium-VLK** [comment]
This is a simple deployment of our published ERC4626 rate provider.  Would be nice if we could have this stamped by next Wednesday the 14th in time for gauge governance next week.

**Comment by mkflow27** [comment]
@zekraken-bot addressed as part of this merge: https://github.com/balancer/code-review/pull/18
