### ISSUE TITLE
instETH Rate Provider Review

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#14]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0x343281bb5029c4b698fe736d800115ac64d5de39#readContract

### Protocol Documentation

https://docs.inceptionlrt.com/introduction/overview

### Protocol Audits

https://docs.inceptionlrt.com/security/audit-reports

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
https://github.com/balancer/code-review/pull/22

**Comment by mkflow27** [comment]
done as per https://github.com/balancer/code-review/pull/22
