### ISSUE TITLE
fix: factory created rate providers can not be found in the registry currently

### ISSUE THREAD

**Issue by gosuto-inzasheru** [balancer/code-review#17]
adding all rate providers to the registry that come from trusted factories could be one option, but at the very least we should have clarity around the security of the factory itself. any rate providers that stem from trusted factories can then be assumed to be safe

so hereby requesting whitelisting/review of the chainlink factory on arbitrum: ~~`0x320CFa1a78d37a13C5D1cA5aA51563fF6Bb0f686`~~

**Comment by Zen-Maxi** [comment]
Do you mean whitelisting for the factory: https://arbiscan.io/address/0x5DbAd78818D4c8958EfF2d5b95b28385A22113Cd#code or the rate provider itself? The address you referenced is the rate provider, not the factory. https://arbiscan.io/address/0x320cfa1a78d37a13c5d1ca5aa51563ff6bb0f686#code

**Comment by gosuto-inzasheru** [comment]
yes sorry indeed, i mean the factory at `0x5dbad78818d4c8958eff2d5b95b28385a22113cd`

**Comment by mkflow27** [comment]
@gosuto-inzasheru This is a broader discussion to have imo. What does marking a factory as safe as part of the registry achieve for you?

The reason I am asking is that any rate provider coming from a safe factory does not necessarily mean that the rate provider will work well with balancer pools due to the downstream dependencies of any external calls it makes.

**Comment by gosuto-inzasheru** [comment]
hmm well in that case i would say we would need to adjust our workflow and ask you guys for some kind of review of the individual factory created oracles, even though they come from a "trusted" factory.

could you elaborate on the downstream dependencies and external calls you mentioned?

**Comment by mkflow27** [comment]
Sorry, I need to clarify. From my perspective once the ChainLink RateProvider factory has been marked as safe everything should be good. However, this is not the case for ERC4626 factories imo. Does this ticket strictly refer to the ChainLink Factory?

**Comment by gosuto-inzasheru** [comment]
ok well that is good news, my request here is then to mark the various `ChainlinkRateProviderFactory` contracts in the registry as safe. oracles created from them can them automatically be assumed safe as well, without reviewing them individually.

not sure what erc4626 factories you are referring to, i guess we can leave that discussion for when an actual factory of that type comes up?

found `ChainlinkRateProviderFactory` on opti: https://optimistic.etherscan.io/address/0x83e443ef4f9963c77bd860f94500075556668cb8

**Comment by gosuto-inzasheru** [comment]
i think this is the `ChainlinkRateProviderFactory` on zkevm: https://zkevm.polygonscan.com/address/0x4132f7acc9db7a6cf7be2dd3a9dc8b30c7e6e6c8#code

**Comment by mkflow27** [comment]
@gosuto-inzasheru Once we merge https://github.com/balancer/code-review/pull/63 I will close this issue. Any factory created RateProvider will be added into the registry.

**Comment by mkflow27** [comment]
@gosuto-inzasheru closing as I have just merged https://github.com/balancer/code-review/pull/63

**Comment by mkflow27** [comment]
closing
