### ISSUE TITLE
genETH rate provider review

### ISSUE THREAD

**Issue by infbque** [balancer/code-review#19]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xC29783738A475112Cafe58433Dd9D19F3a406619#code

### Protocol Documentation

https://docs.genesislrt.com/

### Protocol Audits

https://github.com/genesislrt/contracts/blob/main/projects/liquid-restaking/audits/VAR_GenesisLRT_231221-V1.pdf

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
review merged: https://github.com/balancer/code-review/pull/23
