### ISSUE TITLE
pufETH Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#27]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0x71f80e2CfAFA5EC2F0bF12f71FA7Ea57c3D0c7Af#readProxyContract

### Additional Links

https://etherscan.io/address/0x1025aaa9ceb206303984af4cc831b8a792c363d0#code

### Protocol Documentation

https://docs.puffer.fi/

### Protocol Audits

https://github.com/PufferFinance/pufETH/tree/main/audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by Zen-Maxi** [comment]
Confirming still with pufETH team their upgradeability is properly configured. Aside from this rate seems to be properly configured.

**Comment by mkflow27** [comment]
closing as done here: https://github.com/balancer/code-review/pull/34
