### ISSUE TITLE
Magepie mstETH Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#28]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xcc701e2d472dfa2857bf9ae24c263daa39fd2c61#readContract

### Protocol Documentation

https://docs.magpiexyz.io/

### Protocol Audits

https://docs.magpiexyz.io/security/audit-reports

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
addressed by: https://github.com/balancer/code-review/pull/38
