### ISSUE TITLE
Magpie mswETH Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#29]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xb3351000db2a9a3638d6bbf1c229befeb98377db#readContract

### Protocol Documentation

https://docs.magpiexyz.io/

### Protocol Audits

https://docs.magpiexyz.io/security/audit-reports

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
addressed by: https://github.com/balancer/code-review/pull/38
