### ISSUE TITLE
ERC4626RateProvider and Factory for static aTokens on mainnet, polygon, arbitrum, optimism

### ISSUE THREAD

**Issue by sschuldenzucker** [balancer/code-review#31]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xFC541f8d8c5e907E236C8931F0Df9F58e0C259Ec

### Additional Links

We have deployed Balancer's `ERC4626RateProviderFactory` across mainnet, polygon, arbitrum, and optimism. We have deployed instances of `ERC4626RateProvider` from this factory for `StaticATokenLM`, which is a non-rebasing version of Aave's aTokens that implements ERC4626.

# Mainnet
Factory: https://etherscan.io/address/0xFC541f8d8c5e907E236C8931F0Df9F58e0C259Ec

Instances:
- stataUSDT to USDT at https://etherscan.io/address/0xda3E8CD08753a05Ed4103aF28c69C47e35d6D8Da

# Polygon
Factory: https://polygonscan.com/address/0x3e89cc86307aF44A77EB29d0c4163d515D348313

Instances:
- stataUSDC to USDC at https://polygonscan.com/address/0x7d10050F608c8EFFf118eDd1416D82a0EF2d7531
- stataUSDT to USDT at https://polygonscan.com/address/0x9977a61a6aa950044d4dcD8aA0cAb76F84ea5aCd

# Arbitrum
Factory: https://arbiscan.io/address/0xe548a29631f9e49830be8edc22d407b2d2915f31

Instances:
- stataUSDC to USDC at https://arbiscan.io/address/0x87cD462A781c0ca843EAB131Bf368328848bB6fD
- stataUSDT to USDT at https://arbiscan.io/address/0x48942B49B5bB6f3E1d43c204a3F40a4c5F696ef6

# Optimism
Factory: https://optimistic.etherscan.io/address/0x02a569eea6f85736E2D63C59E60d27d075E75c33

Instances:
- stataUSDC to USDC at https://optimistic.etherscan.io/address/0x4DD03dfD36548C840B563745e3FBeC320F37BA7e
- stataUSDT to USDT at https://optimistic.etherscan.io/address/0x035c93db04E5aAea54E6cd0261C492a3e0638b37

# On the ERC4626RateProvider
We deployed the factories from the source code here: https://github.com/balancer/metastable-rate-providers/tree/master/contracts

We then deployed the rate providers themselves from the factory.

# On the `StaticATokenLM`
This was developed by Aave's devco BGD. Source: https://github.com/bgd-labs/static-a-token-v3/tree/main/src

Audit report: https://github.com/bgd-labs/static-a-token-v3/blob/main/audits/Formal_Verification_Report_staticAToken.pdf

Factory/registry contracts were already deployed on all chains. We took the factory addresses from the [Aave address book](https://github.com/bgd-labs/aave-address-book/tree/main/src), key `STATIC_A_TOKEN_FACTORY`. For some tokens/chains, the corresponding `StaticATokenLM` was already deployed. For the others, we deployed these contracts from the factory. The creation function takes as its only input the address of the underlying (e.g. USDT).

Both the factory and the instances of `StaticATokenLM` are upgradable by Aave governance.

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
addressed here: https://github.com/balancer/code-review/pull/34
