### ISSUE TITLE
jitoSOL Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#40]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://arbiscan.io/address/0x8aa73ec870dc4a0af6b471937682a8fc3b8a21f8#readContract

### Protocol Documentation

https://github.com/jito-foundation/jitosol-wormhole-updater

### Protocol Audits

https://github.com/wormhole-foundation/wormhole/blob/main/SECURITY.md#3rd-party-security-audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
@Zen-Maxi I have created a pr here. https://github.com/balancer/code-review/pull/45 

One important item to mention is that if the rate has not been updated by Wormhole for 7 days, then the call to `getRate` will revert requiring the pool to be moved into recovery mode.
