### ISSUE TITLE
csETH Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#43]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xaC18187f90Bab1081d08dE076a62D1314AAA07C5#code

### Protocol Documentation

https://docs.claystack.com/

### Protocol Audits

https://docs.claystack.com/resources/security#audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
@Zen-Maxi closing this issue as claystack has decided to sunset their services.
