### ISSUE TITLE
Kelp DAO rsETH Rate Provider

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#5]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://zkevm.polygonscan.com/address/0x4186BFC76E2E237523CBC30FD220FE055156b41F#readContract

### Protocol Documentation

https://kelp.gitbook.io/kelp

### Protocol Audits

https://kelp.gitbook.io/kelp/audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by Zen-Maxi** [comment]
@mkflow27 please note the current owner is an EOA and the team has been requested to change owners to a multisig. Layerzero dependent and does not use IRateProvider from what i can see. Please put rETH as a higher priority than this.

**Comment by Zen-Maxi** [comment]
Ownership has been transferred on both the rate provider contract and the mainnet source contract to multisigs belonging to Kelp DAO. 

Ownership transferred:

ETH mainnet tx: https://etherscan.io/tx/0x116f6d5bba937b82412a4ac11c433f8699b08eadc5909dca8bd2bbf435efbd6c
POL ZKEVM: https://zkevm.polygonscan.com/tx/0x7802cbabb76983a4d87bcaa5252f4e91595a08faae32245f4bad5e2f4466ef15

**Comment by mkflow27** [comment]
@Zen-Maxi addressed in
https://github.com/balancer/code-review/pull/10
https://github.com/balancer/code-review/pull/9

**Comment by mkflow27** [comment]
@Zen-Maxi addressed in
https://github.com/balancer/code-review/pull/10
https://github.com/balancer/code-review/pull/9
