### ISSUE TITLE
GBP/USD rate provider 

### ISSUE THREAD

**Issue by adamazad** [balancer/code-review#78]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://gnosisscan.io/address/0x92320D3C8Fd6BE59b22eB0eEe330901Fe4617f33#code

### Additional Links

GBP/USD with a whitelist same as #76

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract & all involved downstream contracts are verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by mkflow27** [comment]
Will be addressed as part of https://github.com/balancer/code-review/pull/76
