### ISSUE TITLE
svETH Rate Provider Review

### ISSUE THREAD

**Issue by Zen-Maxi** [balancer/code-review#8]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0xad4bFaFAe75ECd3fED5cFad4E4E9847Cd47A1879#readContract

### Protocol Documentation

https://vector-reserve.gitbook.io/vector-reserve/introduction/what-is-vector-reserve

### Protocol Audits

https://github.com/JacoboLansac/audits/blob/main/solo/vector-reserve.md

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by Zen-Maxi** [comment]
Hey hoping for 1 week turn around on this, ideally we can vote on a pool/gauge including this token and rate contract.

**Comment by marcusblabs** [comment]
@mkflow27  will create the pull request for @danielmkm  to review by the end of day so he can finish it tomorrow

**Comment by mkflow27** [comment]
@Zen-Maxi merged here: https://github.com/balancer/code-review/commit/d8d65f487884c1ed4f3ce0c19de42f62b1cf4dfd closing as done.
