### ISSUE TITLE
Affine UltraEth Rate Provider

### ISSUE THREAD

**Issue by maruf0011** [balancer/code-review#96]
### Type of Smart Contract

Rate Provider

### Contract Source Code

https://etherscan.io/address/0x47657094e3AF11c47d5eF4D3598A1536B394EEc4

### Protocol Documentation

https://affinedefi.gitbook.io/affine-restaking

### Protocol Audits

https://affinedefi.gitbook.io/affine-restaking/security/audit-reports

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract & all involved downstream contracts are verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

**Comment by tmoon** [comment]
New address (ultraETH): https://etherscan.io/token/0xcbC632833687DacDcc7DfaC96F6c5989381f4B47
